/* This file replaces the old <cpus.h> with something based
   on the new <config.h> that is generated by configure.  */

#include <config.h>

/* That should have defined NCPUS.  */
#if NCPUS-0 == 1
#undef MULTIPROCESSOR
#elif NCPUS-0 > 1
#define MULTIPROCESSOR 1
#else
# error "bogus value for NCPUS:" NCPUS
#endif
